# Generated by Django 6.0 on 2025-12-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('platform', models.CharField(blank=True, max_length=100, null=True)),
                ('handle', models.CharField(blank=True, max_length=200, null=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('careers_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('remote', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('html_description', models.TextField(blank=True, null=True)),
                ('apply_url', models.URLField(blank=True, null=True)),
                ('working_type', models.CharField(blank=True, max_length=200, null=True)),
                ('posting_date', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('source_id', models.CharField(blank=True, max_length=255, null=True)),
                ('raw', models.JSONField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['company'], name='jobs_job_company_73ae7f_idx'), models.Index(fields=['posting_date'], name='jobs_job_posting_662bb4_idx')],
                'unique_together': {('source', 'source_id')},
            },
        ),
    ]
