# Generated by Django 6.0 on 2025-12-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='job',
            name='jobs_job_posting_662bb4_idx',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='source_id',
            new_name='external_job_id',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='source',
            new_name='platform',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='posting_date',
            new_name='posted_at',
        ),
        migrations.AlterUniqueTogether(
            name='job',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='fetched_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['posted_at'], name='jobs_job_posted__7edcdf_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['platform', 'external_job_id'], name='jobs_job_platfor_1e8228_idx'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(fields=('platform', 'external_job_id'), name='unique_platform_external_id'),
        ),
        migrations.RemoveField(
            model_name='job',
            name='html_description',
        ),
        migrations.RemoveField(
            model_name='job',
            name='remote',
        ),
        migrations.RemoveField(
            model_name='job',
            name='working_type',
        ),
    ]
