# Generated by Django 5.0.6 on 2025-12-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_jobs_job_posting_662bb4_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-fetched_at']},
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='jobs_job_company_73ae7f_idx',
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='jobs_job_posted__7edcdf_idx',
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='jobs_job_platfor_1e8228_idx',
        ),
        migrations.AddField(
            model_name='job',
            name='company_logo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='location_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='fetched_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
