# Generated by Django 5.0.6 on 2025-12-19 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_delete_company_alter_job_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('domain', models.CharField(blank=True, max_length=200, null=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('platform', models.CharField(blank=True, help_text='Primary ATS platform (greenhouse, lever, ashby, etc.)', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='job',
            name='unique_platform_external_id',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_logo',
        ),
        migrations.AlterField(
            model_name='job',
            name='external_job_id',
            field=models.CharField(help_text='Job ID from external platform', max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='platform',
            field=models.CharField(help_text='Source platform (greenhouse, lever, ashby, workable, etc.)', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.company'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(fields=('platform', 'external_job_id'), name='unique_platform_external_job'),
        ),
    ]
