# Generated by Django 6.0 on 2025-12-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_company_remove_job_unique_platform_external_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
