# Generated by Django 6.0 on 2025-12-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='structured_description',
            field=models.JSONField(blank=True, help_text='Parsed structured data from job description', null=True),
        ),
    ]
