# Generated by Django 6.0.1 on 2026-01-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_add_structured_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='work_type',
            field=models.CharField(blank=True, help_text='Work type: Remote, Hybrid, On-site, etc.', max_length=50, null=True),
        ),
    ]
