# Generated by Django 6.0.1 on 2026-01-07 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_job_work_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='location_country',
        ),
        migrations.RemoveField(
            model_name='job',
            name='work_type',
        ),
    ]
