# Generated by Django 6.0.1 on 2026-01-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_remove_job_location_country_remove_job_work_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='company',
            name='additional_details',
            field=models.JSONField(blank=True, default=dict, help_text='Additional company information (industry, headquarters, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, help_text='Short company description (2 sentences)', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='employees_count',
            field=models.CharField(blank=True, help_text="Number of employees (e.g., '1-10', '11-50', '51-200', '201-500', '501-1000', '1000+')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='founded_date',
            field=models.DateField(blank=True, help_text='Company founding date', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, help_text="Social media links (e.g., {'linkedin': '...', 'twitter': '...', 'github': '...'})", null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, help_text='Company website URL', null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.URLField(blank=True, help_text='Company logo URL', null=True),
        ),
    ]
