# Generated by Django 6.0.1 on 2026-01-11 21:07

from django.db import migrations


def migrate_logos_to_company(apps, schema_editor):
    """Move company logos from Job.company_logo to Company.logo"""
    Job = apps.get_model('jobs', 'Job')
    Company = apps.get_model('jobs', 'Company')
    
    # Group jobs by company and get the most common logo for each company
    companies_updated = {}
    
    for job in Job.objects.filter(company_logo__isnull=False).exclude(company_logo=''):
        company = job.company
        if company.id not in companies_updated:
            # Only update if company doesn't have a logo yet
            if not company.logo:
                company.logo = job.company_logo
                company.save(update_fields=['logo'])
                companies_updated[company.id] = True


def reverse_migrate_logos(apps, schema_editor):
    """Reverse migration - this is a no-op since we can't restore individual job logos"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_add_company_fields'),
    ]

    operations = [
        migrations.RunPython(migrate_logos_to_company, reverse_migrate_logos),
    ]
