# Generated by Django 6.0.1 on 2026-01-11 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_migrate_logo_to_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company_logo',
        ),
    ]
