# Generated by Django 6.0.1 on 2026-04-08 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0023_remove_company_staff_user_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo_upload',
            field=models.ImageField(blank=True, help_text='Uploaded company logo (multipart field name: logo_upload)', null=True, upload_to='employer_logos/'),
        ),
    ]
