# Generated by Django 6.0.1 on 2026-04-08 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0024_company_logo_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='employer_created',
            field=models.BooleanField(default=False),
        ),
    ]
