# Generated by Django 6.0.1 on 2026-04-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0028_remove_company_employer_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='apply_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
