# Generated by Django 6.0.1 on 2026-05-17 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0029_job_apply_url_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_user_id', models.CharField(db_index=True, help_text='User id from breneo-api (string)', max_length=255)),
                ('applied_at', models.DateTimeField(help_text='When the user applied')),
                ('status', models.CharField(blank=True, choices=[('applied', 'Applied'), ('reviewed', 'Reviewed'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], default='applied', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
            options={
                'db_table': 'job_applications',
                'ordering': ['-applied_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('external_user_id', 'job'), name='uniq_job_application_user_job')],
            },
        ),
    ]
