# Generated by Django 6.0.1 on 2026-05-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0030_job_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, help_text='Set when the user withdraws the application (soft delete)', null=True),
        ),
    ]
