# Generated by Django 6.0.1 on 2026-05-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0031_job_application_withdrawn'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='external_user_email',
            field=models.EmailField(blank=True, default='', help_text='Applicant email from breneo-api / BFF at apply time', max_length=254),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='external_user_name',
            field=models.CharField(blank=True, default='', help_text='Applicant first name at apply time', max_length=255),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='external_user_surname',
            field=models.CharField(blank=True, default='', help_text='Applicant last name at apply time', max_length=255),
        ),
    ]
