# Generated by Django 6.0.1 on 2026-07-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0036_job_applicant_cv_view_acknowledged'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='apply_email',
            field=models.EmailField(blank=True, help_text='Email to send applications to when no apply_url is provided', max_length=254, null=True),
        ),
    ]
