# Generated by Django 6.0.1 on 2026-07-07 16:14

from django.conf import settings
from django.db import migrations, models


def copy_user_fk_to_external_user_id(apps, schema_editor):
    Interview = apps.get_model("interview_api", "Interview")
    User = apps.get_model(*settings.AUTH_USER_MODEL.split("."))

    for interview in Interview.objects.iterator():
        try:
            user = User.objects.get(pk=interview.user_id)
        except User.DoesNotExist:
            interview.external_user_id = str(interview.user_id)
        else:
            username = getattr(user, "username", "") or ""
            if username.startswith("breneo_"):
                interview.external_user_id = username.removeprefix("breneo_")
            else:
                interview.external_user_id = username or str(user.pk)
        interview.save(update_fields=["external_user_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("interview_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="external_user_id",
            field=models.CharField(db_index=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.RunPython(copy_user_fk_to_external_user_id, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="interview",
            name="user",
        ),
        migrations.RenameField(
            model_name="interview",
            old_name="external_user_id",
            new_name="user_id",
        ),
    ]
