# Generated by Django 6.0.7 on 2026-07-07 20:53

import interview_api.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_api', '0002_replace_user_fk_with_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewattempt',
            name='audio_file',
            field=models.FileField(storage=interview_api.storage.interview_audio_storage, upload_to='interview_records/'),
        ),
    ]
